### ISSUE TITLE
Support got git signs?

### ISSUE THREAD

**Issue by qazip** [eddyekofo94/gruvbox-flat.nvim#1]
It would be nice if this theme supported git-signs (https://github.com/lewis6991/gitsigns.nvim). As it is, both the gutter and git hunks look weird, very hard to see.

**Comment by eddyekofo94** [comment]
I can change the colors, I prefer [these](https://github.com/eddyekofo94/gruvbox-flat.nvim/blob/30b7dc9ba83874427271913b0c7b8eb1489bf3b2/lua/gruvbox/colors.lua#L40) But I will add a feature where the user can adjust the colours to their desire. If you want you can suggest

**Comment by eddyekofo94** [comment]
try PackerUpdate, I changed the colours :)
