### ISSUE TITLE
Error when starting vim

### ISSUE THREAD

**Issue by max397574** [eddyekofo94/gruvbox-flat.nvim#10]
I just get this error:
![Screen Shot 2021-07-03 at 09 47 13](https://user-images.githubusercontent.com/81827001/124347246-e3276100-dbe3-11eb-8709-a8be7e360f3d.png)
When I hit ENTER there is no colorscheme:
![Screen Shot 2021-07-03 at 09 49 51](https://user-images.githubusercontent.com/81827001/124347268-03efb680-dbe4-11eb-859a-ef12bea4823b.png)
(random test file)

Init.vim:
https://github.com/max397574/Vim_Config

**Comment by eddyekofo94** [comment]
I tried getting this to work with no success. I don't know why. I am more familiar with Packer and Lua setup. Thanks.

**Comment by kotokrad** [comment]
In my case it was caused by collision with another lua module named "gruvbox" e.g. [gruvbox.nvim](https://github.com/ellisonleao/gruvbox.nvim). Try using more specific name like "gruvbox_flat".
