### ISSUE TITLE
[Feature Request] Override TabLineSel

### ISSUE THREAD

**Issue by gregorias** [eddyekofo94/gruvbox-flat.nvim#12]
Is it possible to override a specific highlight group? 

I'd specifically like to override the colours for TabLineSel, because I don't like the choice of the bright blue background. It pops out more than Normal, which in turns makes my mind always confuse inactive buffers with the active buffer in a plugin like [barbar](https://github.com/romgrk/barbar.nvim). 

I've tried running `vim.cmd[[highlight TabLineSel guifg=#cab181 guibg=#1a1a1a]]` before and after running `  vim.cmd[[colorscheme gruvbox-flat]]` but that didn't seem to work. It seemed as if gruvbox-flat was changing that highlight group back to default.

**Comment by eddyekofo94** [comment]
Hmmmn will look into it when I have time. Try adding TabLineSel to theme.lua files... follow the examples there and make a PR if you have to. Extremely busy at the moment. thanks.
