### ISSUE TITLE
Highlighted cursor selection

### ISSUE THREAD

**Issue by samrath2007** [eddyekofo94/gruvbox-flat.nvim#18]
The original gruvbox has highlights for all selections(in visual mode).  Could this be implemented here?

**Comment by eddyekofo94** [comment]
Yes, I have it implemented on my local branch with specific personal settings. If I get enough support for it I might merge it to the master branch.

**Comment by samrath2007** [comment]
I'm just using the branch now, could you add that option in the readme?

**Comment by eddyekofo94** [comment]
A PR would be nice 😅
