### ISSUE TITLE
Telescope preview border color same as bg color in dark mode

### ISSUE THREAD

**Issue by h4rr9** [eddyekofo94/gruvbox-flat.nvim#3]
the border for Telescope previewer  is the same as bg color when `let g:gruvbox_flat_style = "dark"`

In `lua/gruvbox/colors.lua`

both `colors.bg` and `colors.border` are `#282828`

with `let g:gruvbox_flat_style = "dark"`
![image](https://user-images.githubusercontent.com/22914630/119868317-84aff880-bf3c-11eb-8638-77e2232e941c.png)

without `let g:gruvbox_flat_style = "dark"`
![image](https://user-images.githubusercontent.com/22914630/119868368-96919b80-bf3c-11eb-8c54-e6b2a4bfd422.png)

**Comment by eddyekofo94** [comment]
II personally prefer it that way. Maybe I will set it as my personal config and revert it. Thanks for the heads up

**Comment by rigby-dane** [comment]
This also occurs on LspSagaHoverBorder/AutoPreview border etc. That one feels a lot more clunky when the hover/preview blends into the background.
