### ISSUE TITLE
Colors are missing on FTerm.

### ISSUE THREAD

**Issue by marcelarie** [eddyekofo94/gruvbox-flat.nvim#4]
First I want to say thank you, I really love the color scheme that you made. Really beautiful. 
You made me change my gruvbox classic  that I have been using for years now :D.

I found the autocomplete text color  is missing when I use the [Fterm  plugin. ](https://github.com/numToStr/FTerm.nvim)
 **This is on [gruvbox-flat.nvim](https://github.com/eddyekofo94/gruvbox-flat.nvim)**
![image](https://user-images.githubusercontent.com/62728887/119979488-53c2d880-bfbb-11eb-9deb-0828f4357a23.png)
**This is on [lifepillar/vim-gruvbox8](https://github.com/lifepillar/vim-gruvbox8)**
![image](https://user-images.githubusercontent.com/62728887/119979591-6f2de380-bfbb-11eb-98c5-aa67747229e9.png)

I use zsh on kitty terminal and my version is `NVIM v0.5.0-dev+1351-g109fb5158`

**Comment by eddyekofo94** [comment]
Hey, I've been working on a [quick fix](https://github.com/numToStr/FTerm.nvim/issues/23#issue-905536363) but it seems to not be working. I will take a look at it again. Meanwhile you can try the solution locally and tell me if you got anything.

**Comment by marcelarie** [comment]
I will try, thanks!!
