### ISSUE TITLE
Module gruvbox not found

### ISSUE THREAD

**Issue by Sebastian-Soto-M** [eddyekofo94/gruvbox-flat.nvim#8]
I tried to use your theme but the following showed up when I did
![error image](https://user-images.githubusercontent.com/68821833/122328586-2cda3100-ceed-11eb-9098-6e76b6f9698c.png)

**Comment by eddyekofo94** [comment]
Can I see your config? I can guess what's wrong but I need to be sure.

**Comment by eddyekofo94** [comment]
[This](https://github.com/Sebastian-Soto-M/nvim/blob/2785c3d3f9bf2379a30408bffbf0818310a04911/lua/plugins/_packer.lua#L62) since the theme is written in lua, you shouldn't have it as `opt` because you need the theme at start time. Remove the `opt` then it should work just fine.

**Comment by Sebastian-Soto-M** [comment]
I did what you said but the message is still there.
What can I do to provide you with data for you to fix this issue, screen-shots, specific configurations?

**Comment by eddyekofo94** [comment]
If I close you nvim will it work out of the box? Do I need to install anything? And plus… which branch is your latest configs on?

**Comment by Sebastian-Soto-M** [comment]
You should have packer installed, and you could use the main branch. If there is something missing that I didn't tell you about, let me know and I'll try to respond as fast as possible

**Comment by eddyekofo94** [comment]
Tried your configs and it worked fine for me with [these](https://github.com/Sebastian-Soto-M/nvim/pull/1) minute changes.

**Comment by Sebastian-Soto-M** [comment]
The only thing I did not try from your changes was the 'use {...}' because it was included in the main statement, I'll try this out when I get home and let you know. You said it worked, so maybe I need to clear packer or something in case your change does not work. Thank you for your help!

**Comment by eddyekofo94** [comment]
No problem. You need to have the theme on the runtime at start time, that was the problem. You're welcomed

**Comment by Sebastian-Soto-M** [comment]
In the end, all I needed to do was to remove the ~/.local/share/nvim/site/pack folder and install all my plugins again, it could have been some cache thing or the download order, I really don't know... but it's working now. Thank you for your quick response.
