### ISSUE TITLE
Add highlight on the equals?

### ISSUE THREAD

**Issue by zetashift** [eddyekofo94/gruvbox-flat.nvim#9]
I'm not sure what highlight group to specifiy specifically or how to find it out but I want operators like `>`, `<`, `=`, `==`, `>=` etc etc. to be of color: `#E78A4E` (just like the VSCode theme), I am using `treesitter` but would like it for all filetypes if possible.

Any hints or solutions how to tackle this?

**Comment by eddyekofo94** [comment]
[This](https://github.com/eddyekofo94/gruvbox-flat.nvim/blob/4e6615e601ce6861dddc6533532a7901fd0a68a4/lua/gruvbox/theme.lua#L222): `    TSOperator = { fg = c.fg }, -- For any operator: `+`, but also `->` and `*` in C.`
Change that colour and you'll see the difference

**Comment by zetashift** [comment]
How would I change that color from my config? I tried  `gruvbox_colors` and then adding a `TSOperator` key/value but that didn't work.

**Comment by eddyekofo94** [comment]
@zetashift I am not sure my guessing would be `highlight TSOperator ctermfg=NONE ctermbg=NONE guifg=#E78A4E guibg=NONE
`

**Comment by zetashift** [comment]
I saw that the highlight got added by your PR, thanks a lot! :D
